### PR TITLE
Extract includes

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by nkubala** [comment]
@Androbin could you explain what this is for? are you running into compilation issues?

**Comment by Androbin** [comment]
This refactoring is supposed to separate concerns.
* C code, mostly but not limited to, includes
* Shell code, generating Go code

This also makes both of these easier to change.

The change in lines 20 and 30 is because `-eq` is for integers and `=` for strings.
And `ccflags` was assigned `"$@"` (array), should be `"$*"` (string, concatenation).

**Comment by dlorenc** [comment]
Hey,

So these directories are currently managed by our vendoring tool (we use them as dependencies, and check them into git). We don't currently make changes directly to them manually. I'd suggest sending these fixes upstream to those repositories.

**Comment by Androbin** [comment]
@dlorenc Okay, thanks.

**Pull request closed without merging**
